import Link from './route-transition';
import { ArrowUpRight, ArrowRight, Download } from 'lucide-react';
import type { Metadata } from 'next';
import { products, services, siteUrl, stories } from './data';

export function metadataFor(title:string,description:string,path=''):Metadata {
  return {title,description,alternates:{canonical:siteUrl+path},openGraph:{title,description,url:siteUrl+path,siteName:'WESOUL',type:'website',images:[{url:siteUrl+'/images/hero.webp',alt:'WESOUL — Give Ideas a Soul'}]},twitter:{card:'summary_large_image',title,description,images:[siteUrl+'/images/hero.webp']}};
}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
export function Breadcrumbs({items}:{items:{name:string;href:string}[]}){return <><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map((item,i)=><span key={item.href}><span aria-hidden="true">/</span>{i===items.length-1?<span aria-current="page">{item.name}</span>:<Link href={item.href}>{item.name}</Link>}</span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',href:'/'},...items].map((item,i)=>({'@type':'ListItem',position:i+1,name:item.name,item:siteUrl+item.href}))}}/></>;}
export function PageHero({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:React.ReactNode}){return <section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="page-intro">{description}</p>}{children}</section>;}
export function Flow({steps,label='Workflow'}:{steps:string[];label?:string}){return <ol className="flow" aria-label={label}>{steps.map((step,i)=><li key={i}><span className="flow-number">{String(i+1).padStart(2,'0')}</span><span>{step}</span>{i<steps.length-1&&<ArrowRight size={16} aria-hidden="true"/>}</li>)}</ol>;}
export function CTA({title='What should we bring to life next?',label='Start a Conversation',topic,description='Bring us the idea, problem, process or system you want to improve.'}:{title?:string;label?:string;topic?:string;description?:string}){return <section className="contact section compact-contact"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>{title}</h2><div className="contact-bottom"><p className="cta-copy">{description}</p><Link className="button dark" href={'/contact'+(topic?'?topic='+encodeURIComponent(topic):'')}>{label}<ArrowUpRight size={18}/></Link></div></section>;}
export function ServiceCards(){return <div className="service-cards">{services.map((s,i)=><Link className="service-card" href={'/'+s.slug} key={s.slug}><div className="card-top"><span>0{i+1} / {['BUILD','AUTOMATE','EVOLVE','STRENGTHEN'][i]}</span><ArrowUpRight size={24}/></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div></Link>)}</div>;}
export function WorkCards(){return <div className="work-cards">{stories.map((s,i)=><article className="work-card" key={s.slug}><span className="eyebrow">0{i+1} / {s.sector}</span><h3><Link href={'/work/'+s.slug}>{s.title}</Link></h3><dl><dt>The problem</dt><dd>{s.problem}</dd><dt>What we built</dt><dd>{s.built}</dd><dt>Intended outcome</dt><dd>{s.outcome}</dd></dl><Link className="card-link" href={'/work/'+s.slug}>Explore the product story<ArrowUpRight size={17}/></Link></article>)}</div>;}
export function FAQ({items}:{items:{q:string;a:string}[]}){return <section className="section faq-section"><div><p className="eyebrow">A FEW USEFUL ANSWERS</p><h2>Good questions.<br/><span>Clear answers.</span></h2></div><div>{items.map(item=><details className="faq" key={item.q}><summary>{item.q}<span aria-hidden="true">+</span></summary><p>{item.a}</p></details>)}</div><JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}}/></section>;}
export function Footer(){return <footer><div className="footer-top"><div><Link className="brand footer-small-brand" href="/">WE<span>SOUL</span></Link><p>Software, products and practical AI<br/>built around real business problems.</p><a className="profile-link" href="/wesoul-profile.pdf" download><Download size={16}/>Company profile <span>PDF</span></a></div><div><h2>Company</h2>{[['About','/about'],['Our Work','/work'],['Insights','/insights'],['Contact','/contact']].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</div><div><h2>Services</h2>{services.map(s=><Link key={s.slug} href={'/'+s.slug}>{s.name}</Link>)}</div><div><h2>Products</h2>{products.map(p=><Link key={p.slug} href={'/products/'+p.slug}>{p.name}</Link>)}</div><div><h2>Let’s talk</h2><a href="mailto:info@wesoul.net">info@wesoul.net</a><Link href="/">www.wesoul.net</Link><Link href="/contact">Start a Conversation ↗</Link></div></div><Link className="footer-brand" href="/" aria-label="WESOUL home">WE<span>SOUL</span><span className="footer-dot">✳</span></Link><div className="footer-bottom"><span>© {new Date().getFullYear()} WESOUL. All rights reserved.</span><div className="utility-links"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms</Link><Link href="/cookies">Cookie Policy</Link></div><a href="#main">Back to top ↑</a></div></footer>;}
