'use client';
import { useEffect, useState } from 'react';
import { Menu, X, Plus, Minus, Code2, Smartphone, Workflow, Sparkles, Users, Download, Mail } from 'lucide-react';
export default function Home() {
 const [menu,setMenu]=useState(false);
 return <><a className="skip-link" href="#about">Skip to content</a><header className="header"><a className="brand" href="#home" aria-label="WESOUL home"><img src="/images/mark.png" alt=""/><span>WE<span>SOUL</span></span></a><nav className={menu?'nav open':'nav'}><a href="#about" onClick={()=>setMenu(false)}>Our story</a><a href="#expertise" onClick={()=>setMenu(false)}>Expertise</a><a href="#work" onClick={()=>setMenu(false)}>Selected work</a><a href="#contact" className="nav-cta" onClick={()=>setMenu(false)}>Let’s talk</a></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><main><section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">SOFTWARE & PRODUCT ENGINEERING</p><h1>Give ideas<br/>a <span className="soul">Soul<span className="period">.</span></span></h1><p className="hero-description">Good ideas deserve more than a possibility.<br/>We build the software that brings them to life.</p><div className="hero-actions"><a className="button orange" href="#work">Explore our work</a><a className="text-link" href="#contact">Build with us</a></div><div className="hero-note"><span className="small-star">✳</span><p>Ideas to products.<br/><strong>Technology to impact.</strong></p></div></div><div className="hero-art"><img src="/images/hero.webp" alt="An orange pathway rises through architectural forms"/><span className="art-label">THINK. BUILD. EVOLVE.</span><span className="art-index">W / 01</span></div><div className="hero-bottom"><span>Built around real work. Designed for what’s next.</span><span>SCROLL TO EXPLORE <span className="scroll-line"/></span></div></section><PortfolioSections/></main></>;
}
const products = [
 {name:'Calliper', category:'Healthcare', image:'calliper', tagline:'From reactive fixes to planned care.', description:'A connected platform for biomedical service operations. Equipment, preventive maintenance, inspections, compliance and billing — in one place.', detail:'Built for biomedical teams managing scattered equipment records and missed maintenance. Calliper brings visibility to service operations across clinics and hospitals.', tags:['Asset management','Maintenance','Compliance']},
 {name:'SpanPOS', category:'Retail', image:'spanpos', tagline:'Connected retail. Stronger businesses.', description:'A retail operations platform that connects sales, inventory, customers, payments, installments and reporting.', detail:'Designed around the realities of Pakistani retail, SpanPOS connects store operations to reduce manual reconciliation and give teams a clearer view of their business.', tags:['Point of sale','Inventory','Reporting']},
 {name:'OrbitLedger', category:'Finance', image:'orbitledger', tagline:'Your money. Your data. Your control.', description:'A privacy-first, offline mobile app for personal finance — designed around the way people actually manage money.', detail:'Budgets, committees, cash tracking and debt management in a simple mobile experience. Built with zero data collection and no need to share your financial information.', tags:['Offline first','Mobile','Privacy']},
 {name:'Sayitdone', category:'AI & automation', image:'sayitdone', tagline:'From conversation to action.', description:'Conversational and agentic service execution that connects requests to useful actions.', detail:'Part of WESOUL’s product portfolio focused on turning conversational interactions into service execution and practical workflows.', tags:['Conversational AI','Agentic workflows']},
 {name:'Reqzly', category:'AI & automation', image:'reqzly', tagline:'Less friction. Better workflows.', description:'Procurement workflows and enterprise process automation, built around real operational needs.', detail:'A product focused on procurement workflow and enterprise process automation — bringing structure to the work that happens between teams.', tags:['Procurement','Enterprise automation']},
 {name:'PackVerity', category:'Retail', image:'packverity', tagline:'Clarity in every order.', description:'E-commerce verification, evidence and operational control for the work behind every order.', detail:'A product focused on e-commerce verification and evidence, helping bring operational control to commerce workflows.', tags:['E-commerce','Verification','Operational control']},
];
const services = [
 {icon:Code2,title:'Software & product engineering',text:'From an early idea to a production-ready product. We design and build software around your workflows, your users and your business.',tags:'Product discovery · Web applications · Custom software'},
 {icon:Smartphone,title:'Mobile experiences',text:'Secure, high-performance mobile applications that keep your people connected and productive wherever work happens.',tags:'Mobile products · Field operations · Connected teams'},
 {icon:Sparkles,title:'AI that gets work done',text:'Chatbots, copilots, agents and intelligent workflows that answer questions, use your knowledge and take useful action.',tags:'AI agents · Document intelligence · Knowledge systems'},
 {icon:Workflow,title:'Architecture & integration',text:'Connect the systems you already use. Modernize what matters. Build a foundation that can grow with your business.',tags:'APIs & data flows · Cloud infrastructure · Modernization'},
 {icon:Users,title:'Engineering augmentation',text:'Add focused capability to your team with engineers, product support and AI expertise. Your team stays your team.',tags:'Frontend · Backend · Mobile · Technical consulting'},
];
function PortfolioSections(){
 const [filter,setFilter]=useState('All work');
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 return <>
 <section className="trusted"><p>IN GOOD COMPANY</p><div><span>Brien Holden<br/><b>FOUNDATION</b></span><span className="client-serif">F&H <i>Events</i></span><span>GROWVERT</span><span>BITSIFY<span className="client-small">TECHNOLOGIES</span></span><span className="client-wide">METLUQ</span><span className="client-light">VEARZ</span></div></section>
 <section id="about" className="section about reveal"><div className="section-label">01 / OUR STORY</div><div><h2>The idea stayed.<br/><span>We grew into it.</span></h2><div className="about-copy"><p>We started by helping ideas find their first digital form. Then websites became applications. Applications became products. Products became systems that needed to connect, scale and keep evolving.</p><p>So we evolved too. Today, WESOUL builds software, digital products, mobile applications and intelligent systems for businesses that need technology to do more than simply exist.</p></div><div className="principles"><span>Understand the idea.</span><span>Give it purpose.</span><span>Bring it to life.</span></div></div></section>
 <section className="expertise section" id="expertise"><div className="section-heading reveal"><div><p className="eyebrow">02 / WHAT WE DO</p><h2>Start with the problem.<br/><span>Build what matters.</span></h2></div><p>Technology earns its place when<br/>the business feels the difference.</p></div><div className="service-list">{services.map((s,i)=><details key={s.title} className="service reveal" open={i===0}><summary><span className="service-number">0{i+1}</span><s.icon className="service-icon" strokeWidth={1.3}/><h3>{s.title}</h3><Plus className="plus"/><Minus className="minus"/></summary><div className="service-content"><p>{s.text}</p><span>{s.tags}</span></div></details>)}</div></section>
 <section className="work section" id="work"><div className="section-heading reveal"><div><p className="eyebrow">03 / SELECTED WORK</p><h2>Real problems.<br/><span>Purpose-built products.</span></h2></div><p>Six products. Different industries.<br/>One consistent product discipline.</p></div><div className="filters" role="group" aria-label="Filter products">{['All work','Healthcare','Retail','Finance','AI & automation'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}{f==='All work'&&<sup>06</sup>}</button>)}</div><div className="product-grid" aria-live="polite">{products.filter(p=>filter==='All work'||p.category===filter).map((p)=><article className="product" key={p.name}><div className="product-image"><img loading="lazy" src={'/images/'+p.image+'.webp'} alt={p.name+' artwork from the WESOUL corporate profile'}/><span>{p.category}</span></div><div className="product-title"><h3>{p.name}</h3><span>W / {String(products.indexOf(p)+1).padStart(2,'0')}</span></div><h4>{p.tagline}</h4><p>{p.description}</p><details className="product-details"><summary>Explore product <Plus size={17}/></summary><div><p>{p.detail}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></details></article>)}</div></section>
 <section className="statement"><div className="statement-track" aria-hidden="true">BUILD WITH PURPOSE. <span>EVOLVE WITH SOUL.</span> BUILD WITH PURPOSE. <span>EVOLVE WITH SOUL.</span></div><span className="sr-only">Build with purpose. Evolve with soul.</span></section>
 <section className="section process" id="process"><div className="section-heading reveal"><div><p className="eyebrow">04 / HOW WE BUILD</p><h2>Good software starts<br/><span>before the first line.</span></h2></div><p>Business understanding. Product thinking.<br/>Engineering discipline. Human ownership.</p></div><div className="process-grid">{[{title:'Understand & define',body:'We start with the business problem, the people and the outcomes. Then we turn that understanding into clear requirements and priorities.'},{title:'Design & architect',body:'We shape the experience and the system together, making deliberate choices for usability, security and future growth.'},{title:'Build & validate',body:'We build in focused cycles, test in real conditions and validate the work before it reaches your users.'},{title:'Deploy & evolve',body:'Launch is a beginning. We support your team, learn from real use and keep improving what matters.'}].map((p,i)=><div className="process-step reveal" key={p.title}><span>0{i+1}</span><h3>{p.title}</h3><p>{p.body}</p></div>)}</div><div className="quality"><span>DISCIPLINE IN EVERY DELIVERY</span><p>Security by design</p><p>Maintainable code</p><p>Testing & validation</p><p>Responsible AI</p></div></section>
 <section className="partnership section" id="partnership"><div className="partnership-image reveal"><img src="/images/partnership.webp" loading="lazy" alt="Collage of collaboration and partnership from WESOUL’s company profile"/></div><div className="partnership-copy reveal"><p className="eyebrow">05 / WORKING TOGETHER</p><h2>More than software.<br/><span>A partner for<br/>what’s next.</span></h2><p>Different problems need different ways of working together. Choose the support that fits your business today — with room to grow tomorrow.</p><div className="engagements">{['Build with us','Extend your team','Modernize what you have','Bring AI into the business'].map((s,i)=><a href={'mailto:info@wesoul.net?subject='+encodeURIComponent(s+' — Project enquiry')} key={s}><span>0{i+1}</span>{s}<Mail size={17}/></a>)}</div><a className="profile-link" href="/wesoul-profile.pdf" download><Download size={17}/> Download our company profile <span>PDF</span></a></div></section>
 <section className="contact section" id="contact"><div className="contact-top reveal"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><span>Ideas. People. Technology.</span></div><h2 className="reveal">What should we<br/>bring to <em>life next?</em></h2><div className="contact-bottom"><a className="button dark" href="mailto:info@wesoul.net?subject=Let%E2%80%99s%20build%20something%20with%20WESOUL"><Mail size={18}/> Let’s talk about your idea</a><div><a href="mailto:info@wesoul.net">info@wesoul.net</a><a href="tel:+923007727981">+92 300 7727981</a></div><p>Understand the idea.<br/>Give it purpose. Bring it to life.</p></div></section>
 <footer><a className="footer-brand" href="#home">WE<span>SOUL</span><span className="footer-dot">®</span></a><div className="footer-bottom"><span>© {new Date().getFullYear()} WESOUL. All rights reserved.</span><span>Software & product engineering</span><a href="#home">Back to top</a></div></footer>
 </>;
}
