import Link from '../route-transition';
import { notFound } from 'next/navigation';
import { ArrowUpRight, Mail } from 'lucide-react';
import { allRoutes, articles, products, servicePages, services, siteUrl, stories } from '../data';
import { Breadcrumbs, CTA, FAQ, Flow, JsonLd, metadataFor, PageHero, ServiceCards, WorkCards } from '../components';
import { ContactForm, ProductGrid } from '../interactive';

type Params={params:Promise<{slug:string[]}>};
export const dynamicParams=false;
export function generateStaticParams(){return allRoutes.map(path=>({slug:path.split('/')}));}
const hubMetadata:Record<string,[string,string]>={
  products:['WESOUL Products | Software Built Around Real Work','Explore WESOUL products for personal finance, biomedical service operations, retail, conversational execution, procurement and e-commerce verification.'],
  work:['Software Case Studies & Our Work | WESOUL','See how WESOUL approaches real operational problems through software products, mobile applications, connected systems and practical digital solutions.'],
  insights:['Insights on Software, Products & AI | WESOUL','Practical insights from WESOUL on AI agents, software product engineering, modernization, digitization, integrations and building technology around real business problems.'],
  contact:['Contact WESOUL | Start a Conversation','Talk to WESOUL about a software product, web or mobile application, AI use case, integration, modernization requirement or engineering support need.'],
  privacy:['Privacy Policy | WESOUL','How this WESOUL website handles preview-form details, browser data and direct email enquiries.'],
  terms:['Website Terms | WESOUL','Information about using the WESOUL website, product descriptions and project enquiries.'],
  cookies:['Cookie Policy | WESOUL','Information about cookies and tracking in the WESOUL website implementation.'],
};
function routeInfo(path:string):[string,string]{
  const standard=servicePages[path as keyof typeof servicePages];
  if(standard)return [standard.title,standard.description];
  if(hubMetadata[path])return hubMetadata[path];
  const [kind,slug]=path.split('/');
  const product=kind==='products'?products.find(p=>p.slug===slug):undefined;
  if(product)return [product.name+' | '+product.headline+' | WESOUL',product.description];
  const article=kind==='insights'?articles.find(a=>a.slug===slug):undefined;
  if(article)return [article.title+' | WESOUL Insights',article.description];
  const story=kind==='work'?stories.find(s=>s.slug===slug):undefined;
  if(story)return [story.title+' | WESOUL Work',story.problem+' '+story.built];
  return ['Page not found | WESOUL','The requested page could not be found.'];
}
export async function generateMetadata({params}:Params){const path=(await params).slug.join('/');const [title,description]=routeInfo(path);return metadataFor(title,description,'/'+path);}
export default async function ContentPage({params}:Params){
 const path=(await params).slug.join('/');if(!allRoutes.includes(path))notFound();
 const [kind,slug]=path.split('/');
 const product=kind==='products'&&slug?products.find(p=>p.slug===slug):undefined;
 const article=kind==='insights'&&slug?articles.find(a=>a.slug===slug):undefined;
 const story=kind==='work'&&slug?stories.find(s=>s.slug===slug):undefined;
 let content:React.ReactNode;
 if(product)content=<ProductPage product={product}/>;
 else if(article)content=<ArticlePage article={article}/>;
 else if(story)content=<StoryPage story={story}/>;
 else if(path==='products')content=<><Breadcrumbs items={[{name:'Products',href:'/products'}]}/><PageHero eyebrow="WESOUL PRODUCTS / BUILT AROUND REAL WORK" title="A portfolio built around real work." description="WESOUL’s products solve operational problems across personal finance, biomedical services, retail, conversational execution, procurement and e-commerce verification."/><section className="section hub-grid"><ProductGrid filterable/></section><section className="section editorial-band"><p className="eyebrow">ONE CONSISTENT PRODUCT DISCIPLINE</p><h2>Different industries.<br/><span>The same care for the work.</span></h2><p className="section-lead">Different industries. Different users. One consistent approach: understand the work, reduce friction and build software that earns its place in the operation.</p></section><CTA/></>;
 else if(path==='work')content=<><Breadcrumbs items={[{name:'Our Work',href:'/work'}]}/><PageHero eyebrow="OUR WORK / PROBLEMS INTO PRODUCTS" title="Real businesses. Real operational problems." description="Our work is best understood through the problems it solves, not through screenshots alone."/><section className="section hub-grid"><div className="evidence-note"><span className="eyebrow">PRODUCT WALKTHROUGHS</span><p>Explore the problems, approach and intended value behind three WESOUL products. These are product stories; client-specific outcomes and measured results are not claimed.</p></div><WorkCards/></section><CTA/></>;
 else if(path==='insights')content=<InsightsPage/>;
 else if(path==='contact')content=<><Breadcrumbs items={[{name:'Contact',href:'/contact'}]}/><PageHero eyebrow="LET’S START A CONVERSATION" title="What should we bring to life next?" description="You do not need a complete specification. Bring us the idea, the problem, the workflow or the system you want to improve."/><section className="section contact-layout"><div className="contact-info"><span className="contact-asterisk" aria-hidden="true">✳</span><h2>Good things start<br/><span>with a conversation.</span></h2><a href="mailto:info@wesoul.net" className="contact-email"><Mail size={20}/>info@wesoul.net</a><Link href="/">www.wesoul.net ↗</Link><p>Prefer email? Write to us directly.<br/>The form is currently a local preview.</p></div><ContactForm/></section></>;
 else if(['privacy','terms','cookies'].includes(path))content=<PolicyPage type={path}/>;
 else content=<StandardPage path={path}/>;
 const [title,description]=routeInfo(path);
 return <>{content}<JsonLd data={{'@context':'https://schema.org','@type':'WebPage',name:title,description,url:siteUrl+'/'+path,isPartOf:{'@id':siteUrl+'/#website'},about:{'@id':siteUrl+'/#organization'}}}/></>;
}

type BriefSection={label:string;lines:string[]};
function isHeading(line:string){return line.length>10&&line===line.toUpperCase()&&/[A-Z]/.test(line)&&!line.includes('→');}
function NormalHeading({text}:{text:string}){return <>{text.toLowerCase().replace(/^\p{L}/u,c=>c.toUpperCase()).replace(/\bai\b/g,'AI').replace(/\bwesoul\b/g,'WESOUL')}</>;}
function ApprovedSection({section,index}:{section:BriefSection;index:number}){
 const lines=section.lines.filter(l=>!l.startsWith('CTA:'));
 const heading=lines[0]&&isHeading(lines[0])?lines.shift():undefined;
 const cta=section.lines.find(l=>l.startsWith('CTA:'))?.slice(5);
 const steps=lines.find(l=>l.includes('→'));
 const short=lines.filter(l=>l.length<90&&!l.includes('→'));
 const long=lines.filter(l=>l.length>=90&&!l.includes('→'));
 const comparison=section.label.includes('Chatbot vs');
 const architecture=section.label==='Architecture View'||section.label==='AI + Existing Systems';
 return <section className={'section approved-section '+(index%2===0?'tinted-section':'')}><div className="approved-heading"><p className="eyebrow">{String(index).padStart(2,'0')} / {section.label}</p><h2>{heading?<NormalHeading text={heading}/>:section.label}</h2></div><div className="approved-body">
 {comparison?<div className="comparison-table"><table><caption className="sr-only">Chatbot, copilot, agent and agentic workflow compared</caption><thead><tr><th scope="col">Approach</th><th scope="col">What it does</th></tr></thead><tbody>{lines.map(line=>{const [name,...body]=line.split(' — ');return <tr key={name}><th scope="row">{name}</th><td>{body.join(' — ')}</td></tr>})}</tbody></table></div>:
 architecture?<div className="architecture-diagram" aria-label={section.label}>{(section.label==='AI + Existing Systems'?['ERP / CRM / HRMS / DMS / Internal APIs / Databases','WESOUL AI Layer','Employees / Customers / Managers']:lines.filter(l=>l!=='↓')).map((l,i)=><div key={l} className={i===1?'architecture-core':''}><span>{i===0?'01 / CONNECT':i===1?'02 / CONTROL':'03 / ENABLE'}</span><p>{l}</p>{i<2&&<span className="architecture-arrow" aria-hidden="true">↓</span>}</div>)}</div>:
 <>{long.map(l=><p className="body-copy" key={l}>{l}</p>)}{steps&&<Flow steps={steps.split('→').map(s=>s.trim())} label={section.label}/>}<div className={short.length>1?'capability-list':'plain-copy'}>{short.map(l=>{const [name,...rest]=l.split(' — ');return rest.length?<div key={l}><h3>{name}</h3><p>{rest.join(' — ')}</p></div>:<p key={l}>{l}</p>})}</div></>}
 {cta&&<Link className="text-link" href={cta.includes('Products')?'/products':'/contact'}>{cta} ↗</Link>}</div></section>;
}
function StandardPage({path}:{path:string}){
 const page=servicePages[path as keyof typeof servicePages];if(!page)notFound();
 const service=services.find(s=>s.slug===path);
 const hero=page.sections[0];const headings=hero.lines.filter(isHeading);const body=hero.lines.filter(l=>!isHeading(l));
 const name=path==='about'?'About WESOUL':path==='services'?'Services':service!.name;
 const last=page.sections.at(-1)!;const closingCTA=last.lines.find(l=>l.startsWith('CTA:'))?.slice(5)||'Start a Conversation';
 const closeHeading=last.lines.filter(isHeading).join(' ');
 return <><Breadcrumbs items={[{name,href:'/'+path}]}/><PageHero eyebrow={path==='about'?'OUR STORY / THE IDEA STAYED':path==='services'?'WESOUL SERVICES / BUSINESS FIRST':`WESOUL SERVICES / ${service?.short}`} title={headings.join(' ').toLowerCase().replace(/^\p{L}/u,c=>c.toUpperCase()).replace(/\bai\b/g,'AI')} description={body.join(' ')}><Link href={'/contact?topic='+encodeURIComponent(name)} className="button orange">{path==='ai-engineering'?'Discuss an AI Use Case':service?'Discuss Your Project':'Start a Conversation'}<ArrowUpRight size={17}/></Link></PageHero>
 {path==='services'?<section className="section hub-grid service-hub"><ServiceCards/>{services.map((s,i)=><div className="service-overview" key={s.slug}><span>0{i+1}</span><div><h2><Link href={'/'+s.slug}>{s.name}</Link></h2><p>{page.sections[i+1].lines[0]}</p><div className="tags">{page.sections[i+1].lines.slice(1).filter(l=>!l.startsWith('CTA:')).map(l=><span key={l}>{l}</span>)}</div></div><Link href={'/'+s.slug} aria-label={'Explore '+s.name}><ArrowUpRight/></Link></div>)}</section>:page.sections.slice(1,-1).map((section,i)=><ApprovedSection key={section.label} section={section} index={i+1}/>)}
 {service&&<><section className="section related-section"><p className="eyebrow">CAPABILITY IN CONTEXT</p><h2>Explore the thinking.<br/><span>See the product discipline.</span></h2><div className="related-grid"><Link href={'/insights/'+service.article}><span>INSIGHT</span><h3>{articles.find(a=>a.slug===service.article)!.title}</h3><ArrowUpRight/></Link>{service.related.slice(0,2).map(slug=>{const p=products.find(p=>p.slug===slug)!;return <Link href={'/products/'+slug} key={slug}><span>WESOUL PRODUCT</span><h3>{p.name}</h3><p>{p.headline}</p><ArrowUpRight/></Link>})}</div><Link className="text-link" href="/work">Explore related product stories ↗</Link></section><FAQ items={path==='ai-engineering'?[{q:'What is an AI agent?',a:'An AI agent is a software system that can interpret a request, reason over available information, use permitted tools or applications, and perform defined actions toward an outcome. In business environments, agents should operate within clear permissions, controls and approval boundaries.'}]:path==='software-modernization'?[{q:'Can WESOUL modernize an existing application?',a:'Yes. WESOUL works on architecture, APIs, integration and application modernization to evolve existing systems without unnecessarily replacing what already works.'}]:path==='engineering-augmentation'?[{q:'Does augmentation replace our existing team?',a:'No. WESOUL engineers work alongside existing client teams when additional capability or specialist expertise is needed. Your team keeps ownership of the product.'}]:[{q:'When should a business build custom software?',a:'Custom software makes sense when the workflow, product opportunity or operating model cannot be supported effectively by standard software without excessive compromise.'}]}/><JsonLd data={{'@context':'https://schema.org','@type':'Service',name:service.name,description:service.description,url:siteUrl+'/'+path,provider:{'@id':siteUrl+'/#organization'},serviceType:service.name}}/></>}
 <CTA title={closeHeading?closeHeading.toLowerCase().replace(/^\p{L}/u,c=>c.toUpperCase()):undefined} label={closingCTA} topic={name} description={path==='services'?'Good. Start with the problem. We can work out the technology from there.':undefined}/></>;
}
function ProductPage({product:p}:{product:(typeof products)[number]}){
 const service=services.find(s=>s.slug===p.service)!;
 return <><Breadcrumbs items={[{name:'Products',href:'/products'},{name:p.name,href:'/products/'+p.slug}]}/><section className="product-hero"><div><p className="eyebrow">WESOUL PRODUCT / {p.category}</p><p className="product-name-label">{p.name}</p><h1>{p.headline}</h1><p className="page-intro">{p.description}</p><Link className="button orange" href={'/contact?topic='+encodeURIComponent(p.name)}>{p.slug==='orbitledger'?'Ask About OrbitLedger':p.slug==='sayitdone'?'Explore Sayitdone':'Request a Demo'}<ArrowUpRight size={17}/></Link></div><figure><img src={'/images/'+p.slug+'.webp'} width="1000" height="1000" fetchPriority="high" alt={p.name+' concept illustration from the WESOUL company profile'}/><figcaption>Product concept artwork · WESOUL</figcaption></figure></section>
 <section className="section product-problem"><div><p className="eyebrow">01 / THE PROBLEM</p><h2>Start with<br/><span>the actual work.</span></h2></div><div><p className="section-lead">{p.problem}</p><h3>Who {p.name} is for</h3><ul className="clean-list">{p.audience.map(a=><li key={a}>{a}</li>)}</ul></div></section>
 <section className="section tinted-section"><p className="eyebrow">02 / PRODUCT APPROACH</p><h2>A clearer way<br/><span>to move forward.</span></h2><p className="section-lead">{p.approach}</p><div className="product-capabilities">{p.features.map((f,i)=><div key={f}><span>{String(i+1).padStart(2,'0')}</span><h3>{f}</h3></div>)}</div></section>
 <section className="section"><p className="eyebrow">03 / {p.slug==='packverity'?'EVALUATION FRAMEWORK':'THE WORKFLOW'}</p><h2>{p.slug==='packverity'?'Define the verification you need.':'See how the work connects.'}</h2><Flow steps={p.workflow} label={p.name+' workflow'}/></section>
 <FAQ items={p.faq}/><section className="product-capability-link"><span>BUILT BY WESOUL</span><p>Explore the engineering behind our product approach.</p><Link href={'/'+service.slug}>{service.name}<ArrowUpRight size={17}/></Link></section><CTA title={'Let’s explore '+p.name+'.'} label={p.slug==='orbitledger'?'Discuss OrbitLedger':'Request a Demo'} topic={p.name} description="Tell us about your workflow and what you need the product to do."/>
 <JsonLd data={{'@context':'https://schema.org','@type':'SoftwareApplication',name:p.name,description:p.description,url:siteUrl+'/products/'+p.slug,applicationCategory:p.slug==='orbitledger'?'FinanceApplication':'BusinessApplication',creator:{'@id':siteUrl+'/#organization'}}}/></>;
}
function InsightsPage(){return <><Breadcrumbs items={[{name:'Insights',href:'/insights'}]}/><PageHero eyebrow="WESOUL INSIGHTS / IDEAS WITH PURPOSE" title="Practical thinking for what comes next." description="Clear explanations and practical perspectives on software, products, AI and business digitization."/><section className="section hub-grid"><div className="insight-topics" aria-label="Editorial topics">{['AI & Agents','Product Engineering','Software Modernization','Business Digitization','Mobile & Web Engineering','Product Thinking'].map(t=><span key={t}>{t}</span>)}</div><div className="insight-grid">{articles.map((a,i)=><article className="insight-card" key={a.slug}><Link className={'insight-art art-'+i} href={'/insights/'+a.slug} aria-label={'Read '+a.title}><span aria-hidden="true">{['✳','↗','↔'][i]}</span><small>W / THINKING {String(i+1).padStart(2,'0')}</small></Link><p className="eyebrow">{a.category}</p><h2><Link href={'/insights/'+a.slug}>{a.title}</Link></h2><p>{a.description}</p><Link className="card-link" href={'/insights/'+a.slug}>Read the insight<ArrowUpRight size={17}/></Link></article>)}</div></section><CTA label="Talk to WESOUL About This"/></>;}
function ArticlePage({article:a}:{article:(typeof articles)[number]}){return <><Breadcrumbs items={[{name:'Insights',href:'/insights'},{name:a.title,href:'/insights/'+a.slug}]}/><article><PageHero eyebrow={a.category} title={a.title} description={a.description}><p className="article-byline">By WESOUL · <time dateTime="2026-10-02">October 2, 2026</time></p></PageHero><div className="article-layout"><aside className="article-toc"><p>IN THIS INSIGHT</p>{a.sections.map((s,i)=><a key={s.title} href={'#section-'+i}>{s.title}</a>)}</aside><div className="article-body"><div className="answer-block"><span className="eyebrow">THE DIRECT ANSWER</span><p>{a.answer}</p></div>{a.sections.map((s,i)=><section key={s.title} id={'section-'+i}><h2>{s.title}</h2><p>{s.body}</p></section>)}<section className="article-related"><h2>Put the thinking into practice</h2><p>Explore <Link href={'/'+a.service}>{services.find(s=>s.slug===a.service)!.name}</Link> and the product approach behind <Link href={'/products/'+a.product}>{products.find(p=>p.slug===a.product)!.name}</Link>.</p><p className="author-note">WESOUL is a software and product engineering company. These perspectives follow our business-first approach to software, connected systems and practical AI. <Link href="/about">About WESOUL</Link>.</p></section></div></div></article><FAQ items={a.faq}/><CTA label="Talk to WESOUL About This" topic={a.title}/><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:'2026-10-02',dateModified:'2026-10-02',author:{'@type':'Organization',name:'WESOUL',url:siteUrl+'/about'},publisher:{'@id':siteUrl+'/#organization'},mainEntityOfPage:siteUrl+'/insights/'+a.slug,image:siteUrl+'/images/hero.webp'}}/></>;}
function StoryPage({story:s}:{story:(typeof stories)[number]}){const p=products.find(p=>p.slug===s.product)!;return <><Breadcrumbs items={[{name:'Our Work',href:'/work'},{name:p.name,href:'/work/'+s.slug}]}/><PageHero eyebrow={s.sector+' / PRODUCT WALKTHROUGH'} title={s.title} description={s.built}/><div className="story-image"><img src={'/images/'+p.slug+'.webp'} width="1200" height="650" alt={p.name+' product concept artwork'}/><span>Concept artwork · {p.name}</span></div><section className="section story-content"><div className="story-facts"><span>PRODUCT</span><h2>{p.name}</h2><span>CAPABILITY</span><p>{s.capability}</p><span>EVIDENCE TYPE</span><p>Product walkthrough</p></div><div>{[{title:'The problem',body:s.problem},{title:'WESOUL’s approach',body:s.approach},{title:'What we built',body:s.built},{title:'Intended operational value',body:s.outcome}].map(block=><section key={block.title}><h2>{block.title}</h2><p>{block.body}</p></section>)}<Link className="button dark" href={'/products/'+p.slug}>Explore {p.name}<ArrowUpRight size={17}/></Link></div></section><section className="section tinted-section"><p className="eyebrow">THE PRODUCT WORKFLOW</p><Flow steps={p.workflow}/><Link className="text-link" href={'/'+p.service}>Explore the relevant WESOUL capability ↗</Link></section><CTA topic={p.name}/></>;}
function PolicyPage({type}:{type:string}){
 const title=type==='privacy'?'Privacy policy':type==='terms'?'Website terms':'Cookie policy';
 const blocks=type==='privacy'?[{title:'The enquiry form is a local preview',body:'The current form logs the fields you enter to your browser’s developer console and displays an on-screen notification. It does not send those fields to WESOUL or store them in a website database. Avoid entering sensitive information into the preview form.'},{title:'Direct email enquiries',body:'Email links open your email application. If you choose to send an email to info@wesoul.net, your email provider handles that transmission and WESOUL receives the information you include. Contact WESOUL at that address for questions about information you have shared.'},{title:'Website technology',body:'This implementation does not add analytics, advertising trackers or persistent form storage. When deployed, the hosting provider may process request and security logs; its configuration should be reviewed alongside this notice before launch.'}]:type==='terms'?[{title:'Information on this website',body:'This website introduces WESOUL’s services and products. Product descriptions communicate their stated scope; availability, supported integrations, pricing and suitability should be confirmed directly with WESOUL.'},{title:'Project and product enquiries',body:'Sending an enquiry does not establish a service agreement. Any project scope, commercial terms, delivery commitments or product access should be agreed separately with WESOUL.'},{title:'Illustrations and product stories',body:'Product artwork is illustrative. The product walkthroughs describe problems, approaches and intended value. They are not verified client case studies and do not claim measured client results.'}]:[{title:'Cookies in this implementation',body:'The website code does not set analytics, advertising or preference cookies. Navigation, product filtering and the preview enquiry form work without persistent cookie storage.'},{title:'If the website changes',body:'Adding analytics, embedded services, authentication or a live form may change the website’s data and cookie behavior. This notice and any required consent controls should be reviewed before those features are enabled.'}];
 return <><Breadcrumbs items={[{name:title,href:'/'+type}]}/><PageHero eyebrow="WESOUL / WEBSITE INFORMATION" title={title} description="About the current website implementation. Updated October 2, 2026."/><div className="policy-body">{blocks.map(b=><section key={b.title}><h2>{b.title}</h2><p>{b.body}</p></section>)}<p>Questions? <a href="mailto:info@wesoul.net">Contact info@wesoul.net</a>.</p></div></>;
}
